### ISSUE TITLE
Read Cassandra config from App.config or Web.config

### ISSUE THREAD

**Issue by nakhli** [mattvv/hectorsharp#2]
Hello,

It'd be nice to be able to read HectorSharp config²uration from application config file (App.config/Web.config).

Are you planning to implement this feature?

Thanks,
--Chaker

**Comment by kriswill** [comment]
Yes!  I am planning on adding a config section reader for HectorSharp.  It will include things like ring addresses/ports, authentication details, diagnostics, etc.
