### ISSUE TITLE
How to set CF keys with LexicalUUIDType?

### ISSUE THREAD

**Issue by nakhli** [mattvv/hectorsharp#3]
Hello,
I have a cf compared with LexicalUUIDType:
      <ColumnFamily Name="GuidCF" CompareWith="LexicalUUIDType"/>
I'm trying to set values using the following code:
            var guid = Guid.NewGuid();
            string guidKey = Encoding.Default.GetString(guid.ToByteArray()); 
            // NOTE guidKey.Length == 16
            keyspace.Insert(guidKey, new ColumnPath("GuidCF", null, "key"), "value");
But it fails with the following exception:
[InvalidRequestException: UUIDs must be exactly 16 bytes

How to insert values in cf keyed by UUID?

Thanks,
--Chaker

**Comment by kriswill** [comment]
The current Column class doesn't support non-string names or values.  I'm considering design options.  One is to expose the underlying RawName/RawValue so that you can set them to binary values.  The other possibility is to produce a Column<K, V> type which you can use to specify the types.

**Comment by alyssa-dahlberg** [comment]
Arr, I was just trying to figure out how to do this too.  Some built in guidance on how to convert to compatible bytes would be nice too, e.g. would BitConvert.GetBytes((long)123) match the format expected by Cassandra?
